[package]
name = "rocketone"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.0"
sysinfo = "0.29.0"
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
